### ISSUE TITLE
Fix deprecation warnings

### ISSUE THREAD

**Issue by zhubonan** [aiida-vasp/parsevasp#166]
We have lots of warnings emitted in the tests, need to be fixed before they turn into errors in the future.

**Comment by atztogo** [comment]
https://github.com/aiida-vasp/parsevasp/blob/fd8224aa8c780e5c7cae84545bf6b8891ce46504/parsevasp/vasprun.py#L2322

`np.fromstring(element.text, sep=' ')` should be replaced by `float(element.text)`.

By this most of warnings are removed. Then we have two errors:

```
FAILED tests/test_xml_regular.py::test_xml_overflow[0] - Failed: DID NOT RAISE <class 'SystemExit'>
FAILED tests/test_xml_regular.py::test_xml_overflow[1] - Failed: DID NOT RAISE <class 'SystemExit'>
```

This is because `element.text = "****************"`. It seems current implementation is wrong (see below), and this should be correctly handled.

```
In [2]: np.fromstring("****************")
<ipython-input-2-aa7279fdb32f>:1: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  np.fromstring("****************")
Out[2]: array([1.42602582e-105, 1.42602582e-105])
```
